---
- name: "Provision CheckMK server"
  hosts: checkmk-server
  become: true
  pre_tasks:
    - ansible.builtin.include_role: { name: base, tasks_from: pre }
  tasks:
    - ansible.builtin.slurp:
        src: "/opt/omd/sites/{{ checkmk_site }}/var/check_mk/web/automation/automation.secret"
      register: secret
      tags: [always]
    - block:
        - ansible.builtin.copy:
            content: |
              from cmk.gui.cee.userdb.saml2.config import write_certificate_files
              from cmk.gui.utils.script_helpers import gui_context
              import sys

              def main(certificate='builtin', connection_id='google-fokkema', *args):
                  with gui_context():
                      write_certificate_files(certificate, connection_id)

              main(*sys.argv[1:])
            dest: /tmp/cert.py
            mode: '0644'
        - ansible.builtin.command: ~/bin/python3 /tmp/cert.py
          become: true
          become_method: ansible.builtin.su
          become_exe: sudo su -
          become_user: "{{ checkmk_site }}"
          changed_when: false
        - ansible.builtin.file:
            state: directory
            dest: "{{ checkmk_wato }}"
            owner: "{{ checkmk_site }}"
            group: "{{ checkmk_site }}"
            mode: '0755'
        - ansible.builtin.template:
            src: user_connections.mk.j2
            dest: "{{ checkmk_wato }}/user_connections.mk"
            owner: "{{ checkmk_site }}"
            group: "{{ checkmk_site }}"
            mode: '0644'
      tags: [checkmk.saml]
      vars:
        checkmk_conns:
          google-fokkema:
            idp: metadata.xml
        checkmk_domain: demo.xantara-it.nl
        checkmk_server_url: "https://{{ checkmk_domain }}"
        checkmk_saml_base: "{{ checkmk_server_url }}/{{ checkmk_site }}/check_mk"
        checkmk_saml_acs: "{{ checkmk_saml_base }}/saml_acs.py?acs"
        checkmk_saml_entity: "{{ checkmk_saml_base }}/saml_metadata.py?RelayState=google-fokkema"
        checkmk_saml_meta: "{{ checkmk_saml_base }}/saml_metadata.py"
        checkmk_wato: "/opt/omd/sites/{{ checkmk_site }}/etc/check_mk/multisite.d/wato"
    - ansible.builtin.import_tasks: cmk-postgres.yaml
      tags: [postgres]
      vars:
        checkmk_agent_secret: "{{ secret['content'] | b64decode | trim }}"
  roles:
    - checkmk.general.server
  tags:
    - server
  vars:
    checkmk_admin_password: cmkadmin
    checkmk_server_edition: "{{ checkmk_edition }}"
    checkmk_server_version: "{{ checkmk_version }}"
    checkmk_server_sites:
      - name: "{{ checkmk_site }}"
        admin_pw: "{{ checkmk_admin_password }}"
        version: "{{ checkmk_server_version }}"
        state: started
    checkmk_server_url: http://127.0.0.1/

- name: "Provision CheckMK agent"
  hosts: checkmk-agent
  become: true
  pre_tasks:
    - ansible.builtin.slurp:
        src: "/opt/omd/sites/{{ checkmk_agent_site }}/var/check_mk/web/automation/automation.secret"
      register: secret
      tags: [always]
  roles:
    - checkmk.general.agent
  tags:
    - agent
  vars:
    checkmk_server_ip: 127.0.0.1
    checkmk_agent_ip: 127.0.0.1
    checkmk_agent_edition: "{{ checkmk_edition }}"
    checkmk_agent_site: "{{ checkmk_site }}"
    checkmk_agent_version: "{{ checkmk_version }}"

    checkmk_agent_add_host: true
    checkmk_agent_auto_activate: true
    checkmk_agent_discover: true
    checkmk_agent_delegate_api_calls: "{{ inventory_hostname }}"
    checkmk_agent_host_ip: "{{ checkmk_agent_ip }}"
    checkmk_agent_host_name: "{{ inventory_hostname }}"
    checkmk_agent_host_attributes:
      ipaddress: "{{ checkmk_agent_host_ip | default(omit) }}"
      tag_agent: "cmk-agent"
    checkmk_agent_secret: "{{ secret['content'] | b64decode | trim }}"
    checkmk_agent_server: "{{ checkmk_server_ip }}"
