---
- name: "Provision CheckMK server"
  hosts: checkmk-server
  become: true
  tasks:
    - ansible.builtin.slurp:
        src: "/opt/omd/sites/{{ checkmk_site }}/var/check_mk/web/automation/automation.secret"
      register: secret
      tags: [always]
    - import_tasks: cmk-postgres.yaml
      tags: [postgres]
  roles:
    - tribe29.checkmk.server
  tags:
    - server
  vars:
    checkmk_admin_password: cmkadmin
    checkmk_agent_secret: "{{ secret['content'] | b64decode | trim }}"
    checkmk_server_edition: "{{ checkmk_edition }}"
    checkmk_server_version: "{{ checkmk_version }}"
    checkmk_server_sites:
      - name: "{{ checkmk_site }}"
        admin_pw: "{{ checkmk_admin_password }}"
        version: "{{ checkmk_server_version }}"
        state: started
    checkmk_server_url: http://127.0.0.1/

- name: "Provision CheckMK agent"
  hosts: checkmk-agent
  become: true
  pre_tasks:
    - ansible.builtin.slurp:
        src: "/opt/omd/sites/{{ checkmk_agent_site }}/var/check_mk/web/automation/automation.secret"
      register: secret
      tags: [always]
  roles:
    - tribe29.checkmk.agent
  tags:
    - agent
  vars:
    checkmk_server_ip: 127.0.0.1
    checkmk_agent_ip: 127.0.0.1
    checkmk_agent_edition: "{{ checkmk_edition }}"
    checkmk_agent_site: "{{ checkmk_site }}"
    checkmk_agent_version: "{{ checkmk_version }}"

    checkmk_agent_add_host: true
    checkmk_agent_auto_activate: true
    checkmk_agent_discover: true
    checkmk_agent_delegate_api_calls: "{{ inventory_hostname }}"
    checkmk_agent_host_ip: "{{ checkmk_agent_ip }}"
    checkmk_agent_host_name: "{{ inventory_hostname }}"
    checkmk_agent_host_attributes:
      ipaddress: "{{ checkmk_agent_host_ip | default(omit) }}"
      tag_agent: "cmk-agent"
    checkmk_agent_secret: "{{ secret['content'] | b64decode | trim }}"
    checkmk_agent_server: "{{ checkmk_server_ip }}"
