---
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - ansible.builtin.include_role: { name: base, tasks_from: pre }
  post_tasks:
    - ansible.builtin.include_role: { name: base, tasks_from: post }
  roles:
    - base
    - acme
    - ssh
    - users
    - podman
  vars:
    certs:
      demo.xantara-it.nl: []
