---
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - ansible.builtin.include_role: { name: base, tasks_from: pre }
  post_tasks:
    - ansible.builtin.include_role: { name: base, tasks_from: post }
  roles:
    - base
    - certs
    - ssh
    - users
    - podman
  vars:
    domain: demo.xantara-it.nl