---
- community.crypto.openssl_privatekey:
    path: "{{ cert_key }}"
- community.crypto.openssl_csr:
    path: "{{ cert_csr }}"
    privatekey_path: "{{ cert_key }}"
    common_name: "{{ cert }}"

# FIXME: refresh when crt is expired
- ansible.builtin.stat:
    path: "{{ cert_crt }}"
  register: acme_crt_st
- block:
    - ansible.builtin.command:
        cmd: acme-tiny --account-key {{ acme_account_key }} --acme-dir {{ acme_wwwroot }} --directory-url {{ acme_dir }} --csr {{ cert_csr }}
      register: acme_crt
      changed_when: false
    - ansible.builtin.copy:
        dest: "{{ cert_crt }}"
        content: "{{ acme_crt.stdout }}"
        mode: '0755'
  when: not acme_crt_st.stat.exists

- ansible.builtin.template:
    src: ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl-{{ cert }}.conf
    mode: '0755'
  notify: restart httpd
