---
- name: group ssh
  ansible.builtin.group:
    name: ssh
    state: present

- name: admin user group ssh
  ansible.builtin.user:
    name: xantara
    groups: ssh
    append: true

- name: /etc/ssh/sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0660'
  notify:
    - restart sshd

- name: add ssh to firewall
  ansible.posix.firewalld:
    port: "22/tcp"
    state: enabled
    immediate: true
    permanent: true
