---
- ansible.builtin.group:
    name: adm
    state: present

- ansible.builtin.user:
    name: xantara
    groups: adm
    append: true

- ansible.builtin.template:
    src: sudo_adm.j2
    dest: /etc/sudoers.d/adm
    owner: root
    group: root
    mode: '0660'
