---
- community.crypto.openssl_privatekey:
    path: "{{ account_privkey_csr }}"
  notify: restart httpd

- community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ account_privkey_csr }}"
    common_name: "{{ domain }}"
  register: result_csr

- community.crypto.acme_certificate:
    account_key_src: "{{ account_privkey_le }}"
    acme_directory: "{{ account_dir_url }}"
    acme_version: 2
    csr_content: "{{ result_csr.csr }}"
    dest: "{{ account_pubkey_csr }}"
  register: result_le

- block:
    - ansible.builtin.file:
        state: directory
        dest: "{{ wwwroot }}/{{ http_data['resource'] | dirname }}"
    - ansible.builtin.copy:
        dest: "{{ wwwroot }}/{{ http_data['resource'] }}"
        content: "{{ http_data['resource_value'] }}"
    - community.crypto.acme_certificate:
        account_key_src: "{{ account_privkey_le }}"
        acme_directory: "{{ account_dir_url }}"
        acme_version: 2
        csr_content: "{{ result_csr.csr }}"
        dest: "{{ account_pubkey_csr }}"
        data: "{{ result_le }}"
      notify: restart httpd
  when: result_le is changed and domain in challenge
  vars:
    challenge: "{{ result_le['challenge_data'] }}"
    http_data: "{{ challenge[domain]['http-01'] }}"
