- ansible.builtin.package:
    name:
      - acme-tiny
      - mod_ssl
    state: present
  notify: restart httpd
- ansible.builtin.meta: flush_handlers

- community.crypto.openssl_privatekey:
    path: "{{ account_key }}"

- ansible.builtin.include_tasks: cert.yml
  with_dict: "{{ certs }}"
  vars:
    acme_dir: "{{ acme_dir_prod }}"
    cert: "{{ item.key }}"
    cert_key: /etc/pki/tls/private/{{ cert }}.key
    cert_csr: /etc/pki/tls/certs/{{ cert }}.csr
    cert_crt: /etc/pki/tls/certs/{{ cert }}.crt
    domains: "{{ item.value }}"  # FIXME: support SANs
- ansible.builtin.meta: flush_handlers